pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                script {
                    sh ''' echo "Building image of flask app"
                    if [ ! -d "8200Dev-Flask-Final-Project/.git" ]
                    then
                        git clone https://github.com/valeronh/8200Dev-Flask-Final-Project.git 8200Dev-Flask-Final-Project
                        cd 8200Dev-Flask-Final-Project
                        git pull
                    else
                        cd 8200Dev-Flask-Final-Project
                        git pull
                    fi
                    docker build -t valeron12345/flask_app:latest . 
                    docker push valeron12345/flask_app:latest '''
                }
            }
        }
        stage('Test') {
            steps {
                sh ''' cd 8200Dev-Flask-Final-Project
                ./devops/deploy.sh test '''
            }
        }
        stage('Deploy') {
            steps {
                sh ''' cd 8200Dev-Flask-Final-Project 
                ./devops/deploy.sh prod '''
            }
        }
        stage('Clean Up') {
            steps {
                sh ''' ssh ec2-user@test docker system prune -af --volumes
                ssh ec2-user@prod docker system prune -af --volumes
                docker system prune -af --volumes '''
            }
        }
    }
} 
