pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                script {
                    sh ''' echo "Building image of flask app"
                    if [ ! -d "8200Dev-Flask-Final-Project/.git" ]
                    then
                        git clone https://github.com/valeronh/8200Dev-Flask-Final-Project.git 8200Dev-Flask-Final-Project
                        cd 8200Dev-Flask-Final-Project
                        git pull
                    else
                        cd 8200Dev-Flask-Final-Project
                        git pull
                    fi
                    docker build -t valeron12345/flask_app:latest . 
                    docker push valeron12345/flask_app:latest
                    docker system prune -af --volumes '''
                }
            }
        }
        stage('Test') {
            steps {
                sh ''' ssh ec2-user@test docker pull valeron12345/flask_app:latest
                ssh ec2-user@test docker-compose up -d '''
                sleep 10
                sh ''' ssh ec2-user@test ./test.sh
                ssh ec2-user@test docker system prune -af --volumes '''
            }
        }
        stage('Deploy') {
            steps {
                sh ''' ssh ec2-user@prod docker pull valeron12345/flask_app:latest
                ssh ec2-user@prod docker-compose up -d
                ssh ec2-user@prod docker system prune -af --volumes '''
            }
        }
    }
}
