version: "3.8"
services:
  app:
    image: valeron12345/flask_app:latest
    links:
      - mysql
    ports:
      - "5000:5000"
    working_dir: /app
    depends_on:
      - mysql
        
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'valerydb'
      MYSQL_USER: 'valerys'
      MYSQL_PASSWORD: 'Aa1234'
      MYSQL_ROOT_PASSWORD: 'Bb1234'
    volumes:
      - /var/run/mysqlDocker/init:/docker-entrypoint-initdb.d
      - /var/run/mysqlDocker/var:/var/lib/mysql

networks:
  default:
    external: false
    name: app_network
